export const FETCH_MEMES_REQUEST = "FETCH_MEMES_REQUEST";
export const FETCH_MEMES_SUCCESS = "FETCH_MEMES_SUCCESS";
export const FETCH_MEMES_FAIL = "FETCH_MEMES_FAIL";

export const DELETE_MEMES_REQUEST = "DELETE_MEMES_REQUEST";
export const DELETE_MEMES_SUCCESS = "DELETE_MEMES_SUCCESS";
export const DELETE_MEMES_FAIL = "DELETE_MEMES_FAIL";
export const DELETE_MEMES_RESET = "DELETE_MEMES_RESET";

export const ADD_URL_REQUEST = "ADD_URL_REQUEST";
export const ADD_URL_SUCCESS = "ADD_URL_SUCCESS";
export const ADD_URL_FAIL = "ADD_URL_FAIL";

export const UPLOAD_MEME_REQUEST = "UPLOAD_MEME_REQUEST";
export const UPLOAD_MEME_SUCCESS = "UPLOAD_MEME_SUCCESS";
export const UPLOAD_MEME_FAIL = "UPLOAD_MEME_FAIL";